[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/ping"
healthcheckTimeout = 60
healthcheckInterval = 5
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"
PORT = "$PORT"
NPM_CONFIG_LEGACY_PEER_DEPS = "true" 